-- 1. Limpeza inicial (opcional: remove tabelas se já existirem para recriar do zero)
DROP TABLE IF EXISTS tb_credit_analysis;
DROP TABLE IF EXISTS tb_customer;

-- 2. Tabela de Clientes (Dados Cadastrais)
CREATE TABLE tb_customer (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_name VARCHAR(100) NOT NULL,
    cpf VARCHAR(11) NOT NULL UNIQUE, -- CPF deve ser único no sistema
    phone VARCHAR(20) NOT NULL,
    age INTEGER NOT NULL,
    profession VARCHAR(50),
    monthly_income NUMERIC(15, 2) NOT NULL -- Ex: 15000.50 (Precisão financeira)
);

-- 3. Tabela de Análises (Histórico de Crédito)
CREATE TABLE tb_credit_analysis (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id BIGINT NOT NULL,
    
    -- Resultado da Análise
    approved BOOLEAN NOT NULL, -- true = Aprovado, false = Reprovado
    score_value INTEGER NOT NULL, -- 0 a 100
    
    -- Detalhes da Oferta (podem ser NULL se for reprovado)
    approved_limit NUMERIC(15, 2), -- Limite total aprovado
    approved_interest_rate NUMERIC(5, 4), -- Taxa mensal (Ex: 0.0175 para 1.75%)
    max_installments INTEGER, -- Prazo máximo (Ex: 36)
    withdrawal_limit_value NUMERIC(15, 2), -- Valor da parcela máxima (30% renda)
    
    -- Auditoria
    analysis_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP, -- Data/Hora automática
    
    -- Relacionamento (Chave Estrangeira)
    CONSTRAINT fk_customer 
        FOREIGN KEY (customer_id) 
        REFERENCES tb_customer (id)
        ON DELETE CASCADE -- Se apagar o cliente, apaga o histórico (opcional)
);

-- 4. Índices para Performance (Busca rápida por CPF)
CREATE INDEX idx_customer_cpf ON tb_customer(cpf);


-- TABELA: Detalhes da Reprovação
CREATE TABLE tb_rule_violation (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    analysis_id BIGINT NOT NULL,
    rule_name VARCHAR(50) NOT NULL, -- Ex: 'SERASA_SCORE', 'COMMITMENT_LIMIT'
    description VARCHAR(255),       -- Ex: 'Score Serasa abaixo de 300'
    
    CONSTRAINT fk_analysis 
        FOREIGN KEY (analysis_id) 
        REFERENCES tb_credit_analysis (id)
);